POST http://localhost:5000/api/superheroes HTTP/1.1
Content-Type: application/json

{
    "nickname": "Superhero",
    "realName": "Whoo",
    "originDescription": "lorem 123",
    "catchPhrase": "lorem 321",
    "images": [],
    "superPowers": ["Fly", "Jump"]
}