GET http://localhost:5000/api/superheroes HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTRkMTBkYzhjNDYzYzdjZjc5ODAwYTIiLCJlbWFpbCI6InBvdHRlcjEyM0BnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTY5OTY0MjQzNSwiZXhwIjoxNjk5NjQyNDY1fQ.DVEL0cI6THHzdiCROflDGwqPi3USE9elMR1qQlQYXPo