GET http://localhost:5000/api/superheroes HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTRkMTBkYzhjNDYzYzdjZjc5ODAwYTIiLCJlbWFpbCI6InBvdHRlcjEyM0BnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTY5OTYzNzE2NywiZXhwIjoxNjk5NjM3MTk3fQ.-UuJRyAD_qrM2dEO_sqHfwgLpdCth42e8JlTW5ASiGc